apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-logs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /tmp/backend-logs # Directory on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "k8s-w1"
          - "k8s-w2"
          - "k8s-w3"
          - "k8s-w4"