apiVersion: v1
kind: Service
metadata:
  name: emp-mgmt-backend-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: emp-mgmt-backend-app

---
apiVersion: v1
kind: Service
metadata:
  name: emp-mgmt-frontend-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: emp-mgmt-frontend-app