apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: emp-mgmt-backend-netpol
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: emp-mgmt-backend-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: emp-mgmt-frontend-app
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: emp-mgmt-frontend-app