apiVersion: v1
kind: Service
metadata:
  name: emp-mgmt-frontend-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: emp-mgmt-frontend-app